version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8090:8090"  # Mantém a porta 8090 para o serviço 'app'
    environment:
      - SPRING_PROFILES_ACTIVE=dev  # Ativa o perfil 'dev' para configurações específicas do ambiente de desenvolvimento
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydatabase  # URL do banco de dados MySQL
      - SPRING_DATASOURCE_USERNAME=root  # Nome de usuário do banco de dados MySQL
      - SPRING_DATASOURCE_PASSWORD=root  # Senha do banco de dados MySQL
    depends_on:
      - db  # Garante que o serviço 'db' seja iniciado antes do serviço 'app'

  db:
    image: mysql:latest  # Usa a imagem oficial do MySQL
    container_name: mysql-container-blackbox
    environment:
      MYSQL_ROOT_PASSWORD: root  # Define a senha do usuário root do MySQL
      MYSQL_DATABASE: mydatabase  # Define o nome do banco de dados a ser criado
    ports:
      - "3308:3306"  # Mapeia a porta 3308 do host para a porta 3306 do container (alteração para evitar conflito)
    volumes:
      - blackbox_data:/var/lib/mysql  # Mapeia o volume para persistência dos dados do MySQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest  # Usa a imagem oficial do phpMyAdmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db  # Define o host do banco de dados MySQL
      MYSQL_ROOT_PASSWORD: root  # Senha do usuário root do MySQL
    ports:
      - "8081:80"  # Mapeia a porta 8081 do host para a porta 80 do container
    depends_on:
      - db  # Garante que o serviço 'db' seja iniciado antes do serviço 'phpmyadmin'

volumes:
  blackbox_data:  # Volume para persistência dos dados do MySQL
